name: DiscordRoleSync
version: 1.1
api-version: 1.15
main: dev.tycho.DiscordRoleSync.DiscordRoleSync
author: TychoVI
depend:
  - LuckPerms
  - DiscordSRV
commands:
  dc:
    description: Main command for DiscordRoleSync
    usage: /dc