name: DiscordRoleSync
version: 1.0
api-version: 1.14
main: dev.tycho.DiscordRoleSync.DiscordRoleSync
author: TychoVI
depend:
  - LuckPerms
  - DiscordSRV
commands:
  dc:
    description: Main command for DiscordRoleSync
    usage: /dc